version: "3.7"
services:
  db:
    image: postgres:12.1

  web:
    image: trivia
    build:
      context: .
      dockerfile: ./web.dockerfile
      target: dev
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 8060:8000
      - 8061:8080

  api:
    image: trivia
    build:
      context: .
      dockerfile: ./app.dockerfile
    volumes:
      - .:/app
    command: python app.py
    env_file: .env
    ports:
      - 8180:8180
